# GPU Memory Optimized Configuration for NVIDIA RTX 6000 Ada (48GB VRAM)
# Optimized for DigitalOcean Kubernetes clusters  
# Memory allocation: ~40GB available (85% of 48GB)

sampleApplication:
  decode:
    extraArgs:
      - "--max-model-len"
      - "16384"                   # Higher sequence length for 48GB VRAM
      - "--gpu-memory-utilization"
      - "0.85"                    # Use 85% of GPU memory
      - "--kv-cache-dtype"
      - "fp8"                     # Use FP8 for KV cache to save memory
      - "--tensor-parallel-size"
      - "1"                       # Single GPU setup
  prefill:
    extraArgs:
      - "--max-model-len"
      - "16384"
      - "--gpu-memory-utilization"
      - "0.85"
      - "--kv-cache-dtype"
      - "fp8"
      - "--tensor-parallel-size"
      - "1"

# Enable comprehensive metrics collection
modelservice:
  metrics:
    enabled: true
    serviceMonitor:
      interval: 15s
  epp:
    metrics:
      enabled: true
      serviceMonitor:
        interval: 10s
  vllm:
    metrics:
      enabled: true

# Resource requests and limits for RTX 6000 Ada
sampleApplication:
  resources:
    limits:
      nvidia.com/gpu: "1"
      memory: "64Gi"              # Host memory for RTX 6000 Ada nodes
      cpu: "16"
    requests:
      nvidia.com/gpu: "1"
      memory: "32Gi"
      cpu: "8" 